spring.application.name=busca-oferta-api

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
spring.jpa.defer-datasource-initialization=true

# Evolution API
evolution.api.url=${EVOLUTION_API_URL}
evolution.api.instance=pds
evolution.api.apikey=${EVOLUTION_API_KEY}
