@startuml
skinparam roundcorner 5
skinparam class {
    BackgroundColor White
    ArrowColor Black
    BorderColor Black
}
skinparam package {
    BackgroundColor White
    BorderColor Black
}

package "Controller" {
    class ProdutoController {
        - produtoService: ProdutoService
        + criar(ProdutoRequestDTO): ResponseEntity<ProdutoResponseDTO>
        + listar(CategoriaProduto*): List<ProdutoResponseDTO>
    }
    class OfertaController {
        - ofertaService: OfertaService
        + criar(OfertaRequestDTO): ResponseEntity<OfertaResponseDTO>
        + listarPorProduto(Long): ResponseEntity<List<OfertaResponseDTO>>
    }
}

package "DTO" {
    package "Produto " as DTO_Produto {
        class ProdutoResponseDTO
        class ProdutoRequestDTO
    }
    
    package "Oferta " as DTO_Oferta {
        class OfertaResponseDTO
        class OfertaRequestDTO
    }
}

package "Service" {
    class ProdutoService {
        - produtoRepository: ProdutoRepository
        + salvar(ProdutoRequestDTO): ProdutoResponseDTO
        + listarTodos(CategoriaProduto): List<ProdutoResponseDTO>*
    }
    class OfertaService {
        - ofertaRepository: OfertaRepository
        - produtoRepository: ProdutoRepository
        + salvar(OfertaRequestDTO): OfertaResponseDTO
    }
}

package "Model" {
    package "Enums" {
        enum CategoriaProduto <<Enumeration>> {
            ALIMENTOS
            BEBIDAS
            LIMPEZA
            OUTROS
        }
    }
    
    class Produto {
        - id: Long
        - CategoriaProduto: categoria
    }
    
    class Oferta {
        - urlDoProduto: String
        - produto: Produto
        - loja: Loja
    }
}

package "Repository" {
    interface ProdutoRepository <<Interface>> {
        findByCategoria(CategoriaProduto): List<Produto>
    }
    interface OfertaRepository <<Interface>> {
        findByProdutoId(Long): List<Oferta>
    }
}

' Relationships (Dependencies)
ProdutoController ..> DTO_Produto
OfertaController ..> DTO_Oferta

ProdutoService ..> DTO_Produto
OfertaService ..> DTO_Oferta

ProdutoService ..> Produto
ProdutoService ..> ProdutoRepository

OfertaService ..> Oferta
OfertaService ..> OfertaRepository

ProdutoRepository ..> Produto
OfertaRepository ..> Oferta

Oferta ..> Produto
Produto ..> CategoriaProduto

ProdutoRepository ..> CategoriaProduto
ProdutoController ..> CategoriaProduto

@enduml